### ISSUE TITLE
Mon PC il a pris feu

### ISSUE THREAD

**Issue by louisdevie** [DamienChabret/BatmanProgram#1]
J'ai testé le programme avec 500Go et j'ai vu des flammes sortir à l'arrière de mon PC.
Est-ce que c'est normal ?

**Comment by DamienChabret** [comment]
C'est pour augmenter la productivité de votre ordinateur ainsi que ses performances. Voyez-ça comme du nitro.

Bien à vous.

**Comment by louisdevie** [comment]
D'accord, merci !
